### ISSUE TITLE
Configuration changes are not saved between sessions

### ISSUE THREAD

**Issue by riv-dalatorre** [rivelinrobotics/netshape_issues#3]
**Describe the bug**
If the state of the cell changes (for example attached tool changes) during a session, the changes are not saved.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load sim from binary deployment
2. Change tools
3. Close sim and re-launch

**Expected behaviour**
Changes in the session state persist between sessions.

**Additional context**
rivelin-netshape-v001

**Comment by rr-tom-noble** [comment]
Fixed in v003
